Esri/arcgis-maps-sdk-unity-samples

- samples_project/Assets/HDRPDefaultResources/DefaultSettingsVolumeProfile.asset
- samples_project/Assets/HDRPDefaultResources/DefaultSettingsVolumeProfile.asset.meta
- samples_project/Assets/HDRPDefaultResources/FoliageDiffusionProfile.asset
- samples_project/Assets/HDRPDefaultResources/FoliageDiffusionProfile.asset.meta
- samples_project/Assets/HDRPDefaultResources/HDRenderPipelineGlobalSettings.asset
- samples_project/Assets/HDRPDefaultResources/SkinDiffusionProfile.asset
- samples_project/Assets/HDRPDefaultResources/SkinDiffusionProfile.asset.meta
- samples_project/Assets/SampleViewer/Resources/SampleGraphicSettings/HDRP.prefab
- samples_project/ProjectSettings/ProjectSettings.asset
**Summary**
Fixes the HDRP lighting in the samples
**Tests**
Tested on Windows
3653
> fix lighting

- samples_project/Assets/SampleViewer/Samples/Routing/readme.md
**Sample**
**Summary**
This PR is to improve the Readme
- Change the sample name to start with a verb (was requested by DevEx)
- Add "How to use sample" for the information about how users can see the functionality
- Make "How it works" focused on how the sample is done to show the functionality
**Tests**
> Routing readme updates

- templates/readme.md
This is for the Unity sample repo. There are a few words adjusted to use Unity terms.
> Create readme template

- samples_project/Assets/SampleViewer/Samples/FeatureLayer/readme.md
**Sample**
Feature layer
**Summary**
Although the How it works section content structure is different from the UE one it has good information so I haven't update that part.
- update title
- add how to use sample section
- add a link to Unity doc
- fix a bit of formatting
**Tests**
> Feature layer readme improvements

- samples_project/Assets/SampleViewer/Samples/LineOfSight/readme.md
**Sample**
Line of sites
**Summary**
- Add how to use the sample section
- Update how it works section and include the links to docs
- Update the sample title according to the DevEx team's convention. 
**Tests**
read
> Line of sight readme improvements

- samples_project/Assets/SampleViewer/Samples/StreamLayer/StreamLayerWebSocketSubscribe.cs
- samples_project/Assets/SampleViewer/Samples/StreamLayer/readme.md
**Sample**
Stream layer
**Summary**
- Align the page structure with other samples
- Correct terms
- Add links to some pages with more info
- Minor code cleaning
**Tests**
Since I modified the code a bit, tested locally to make sure it still works.
1.2
> Stream layer sample readme improvements

- samples_project/Assets/SampleViewer/Samples/Routing/RouteManager.cs
- samples_project/Assets/SampleViewer/Samples/Routing/Routing.unity
In case this error message shows up (when putting the API key in the project settings)
The UI text is reorganized into this
> Routing UI Text fix

- samples_project/Assets/SampleViewer/Resources/Images/ButtonBorder.png.meta
- samples_project/Assets/SampleViewer/Resources/Images/ButtonBorder_Color.png.meta
- samples_project/Assets/SampleViewer/Resources/Images/Cancel_Icon.png.meta
- samples_project/Assets/SampleViewer/Resources/Images/LClick.png.meta
- samples_project/Assets/SampleViewer/Resources/Images/LShift.png.meta
- samples_project/Assets/SampleViewer/Resources/Images/LogoMenu.png.meta
- samples_project/Assets/SampleViewer/Resources/Images/Pan.png.meta
- samples_project/Assets/SampleViewer/Resources/Images/Reset.png.meta
- samples_project/Assets/SampleViewer/Resources/Images/Rotate.png.meta
- samples_project/Assets/SampleViewer/Resources/Images/Slide.png.meta
- samples_project/Assets/SampleViewer/Resources/Images/Space.png.meta
- samples_project/Assets/SampleViewer/Resources/Images/WASD_Keys.png.meta
- samples_project/Assets/SampleViewer/Resources/Images/Warning_Sign.png.meta
- samples_project/Assets/SampleViewer/Resources/Images/arrow-down.png.meta
- samples_project/Assets/SampleViewer/Resources/Images/arrow-right.png.meta
- samples_project/Assets/SampleViewer/Resources/Images/drop-down.png.meta
- samples_project/Assets/SampleViewer/Resources/Images/information.png.meta
- samples_project/Assets/SampleViewer/Resources/Images/search.png.meta
- samples_project/Assets/SampleViewer/Samples/StreamLayer/StreamLayer.unity
Maximized Game Window
16x9 Aspect Ratio
Before
After
> Fuzzy image fix

- samples_project/Assets/SampleViewer/Samples/StreamLayer/StreamLayerWebSocketSubscribe.cs
This is from this user provided feedback: https://github.com/Esri/arcgis-maps-sdk-unity-samples/issues/77
This is backend work so you won't notice anything in the sample itself, debugging is probably the best way to verify it:
Our original code use a buffer to receive websocket messages, so that if 
1. the websocket sends message in chunks and not at once; or 
2. the websocket send a message that's bigger than the buffer,
we'll receive the incomplete message. 
By using a loop and check `EndOfMessage` we can make sure that we receive the complete message. 
****before fixing:** 
**If the buffer is really small (in this extreme example only 16 bytes), `EndOfMessage` is false indicating that we only receive partial message.****  
****after fixing:**
**Even with the small buffer size, …
> fix websocket message incomplete issue

- samples_project/Assets/SampleViewer/SampleViewer.unity
- samples_project/Assets/SampleViewer/Samples/StreamLayer/readme.md
**Sample**
Stream Layer sample
**Summary**
Disable Stream Layer sample in Sample viewer
**Tests**
Windows
Maps SDK 1.3
> Disable Stream Layer Sample in Sample Viewer

- README.md
**Summary**
Updates readme to mention latest public release (1.4.0).
1.4.0
> Update readme to reference 1.4

- sample_project/Assets/SampleViewer/Samples/ThirdPerson/readme.md
- sample_project/Assets/SampleViewer/Samples/WeatherQuery/readme.md
- xr_sample_project/Assets/SampleViewer/Samples/VRSample/readme.md
- xr_sample_project/Assets/SampleViewer/Samples/XRTableTop/readme.md
> Unifying readme title formats

- sample_project/Assets/SampleViewer/Samples/WeatherQuery/Scripts/WeatherQuery.cs
**Sample**
Weather Query
**Summary**
These using statements are causing issues with standalone builds.
**Tests**
Windows
1.6
> weather sample: remove unnecessary Using statements from `WeatherQuery.cs`

- sample_project/Assets/SampleViewer/Scripts/AutoImport.cs
**Summary**
Moves menu item to be consistent with new location in 1.6.
**Tests**
Windows
1.6
> menus: move "re-import samples materials" menu option

- README.md
- sample_project/Assets/SampleViewer/Resources/SampleGraphicSettings/SampleURPipeline.asset
- sample_project/Packages/packages-lock.json
- sample_project/ProjectSettings/GraphicsSettings.asset
- sample_project/ProjectSettings/ProjectVersion.txt
- sample_project/ProjectSettings/ShaderGraphSettings.asset
- xr_sample_project/Packages/packages-lock.json
- xr_sample_project/ProjectSettings/ProjectVersion.txt
**Summary**
With the 1.6 release, we are updating the minimum Unity version requirements of both sample viewers.
**Tests**
N/A
1.6
> Update Unity versions to `2022.3.35f1`

- sample_project/Assets/SampleViewer/Samples/Geocoding/readme.md
Fixing broken links in Geocoding sample readme file.
> Geocoding readme fix broken links

- sample_project/Assets/SampleViewer/Samples/WeatherQuery/Scripts/ScrollItem.cs
- sample_project/Assets/SampleViewer/Samples/WeatherQuery/Scripts/WeatherQuery.cs
**Sample**
Weather Sample
**Summary**
- Fix an issue where the rain/weather system would come in at an angle
- Change the where clause so that more than 6 entries would should up in the drop down
**Tests**
Windows
Public version 1.6
> Fix Weather Query Sample

- sample_project/Assets/SampleViewer/Samples/WeatherQuery/Scripts/WeatherData.cs
**Sample**
Weather Sample
**Summary**
Sample project can not currently be built in URP because WeatherData.cs references HDRP specific components without any macro definitions.
**Tests**
Windows
Maps SDK 1.6 w/ Unity 2022.3.42
> Bug: Fix Weather Query Build Issue

- sample_project/Assets/SampleViewer/SampleViewer.unity
**Sample**
Sample Switcher
**Summary**
Add a scroll bar to the sample switcher to access all samples
**Tests**
Windows
Maps SDK 1.6 w/ Unity 2022.3.42
> Add Scroll Bar to Sample Switcher

- sample_project/Assets/SampleViewer/Scripts/SampleSwitcher.cs
**Sample**
**Checklist**
Tested with the newest daily.
> Sample viewer: use new API key

- sample_project/Assets/SampleViewer/Scripts/SampleSwitcher.cs
**Summary**
The API key length from ArcGIS is not reliable. This removes the check for length.
**Checklist**
1.6
> api keys: Remove length check

- sample_project/Assets/SampleViewer/Samples/StreamLayer/readme.md
- xr_sample_project/Assets/SampleViewer/Samples/VRSample/readme.md
**Sample**
Fix a few broken links on the read me doc
> Fix broken links

- sample_project/Assets/SampleViewer/SampleViewer.unity
- sample_project/Assets/SampleViewer/Scripts/SampleSwitcher.cs
**Summary**
- Fixed scroll view alignment.
- Resolved URP button color.
- Fix for weather query text.
- Resolved bug where URP button would not remain un-interactable when switching scenes.
- Behavior change - URP button now disappears when viewing HDRP-only scenes.
- Refactored sample switcher script to reduce number of events needed for each UI button.
**Checklist**
1.7
> ui: main menu tweaks

- sample_project/Assets/SampleViewer/Resources/Prefabs/InputManager.prefab
- sample_project/Assets/SampleViewer/Resources/Prefabs/InputManager.prefab.meta
- sample_project/Assets/SampleViewer/Resources/SampleGraphicSettings/SampleURPipeline.asset
- sample_project/Assets/SampleViewer/SampleViewer.unity
- sample_project/Assets/SampleViewer/Samples/FeatureLayer/FeatureLayer.unity
- sample_project/Assets/SampleViewer/Samples/FeatureLayer/Scripts/FeatureLayerInputManager.cs
- sample_project/Assets/SampleViewer/Samples/FeatureLayer/Shaders/Shader Graphs_Outline.mat
- sample_project/Assets/SampleViewer/Samples/Geocoding/Geocoder.cs
- sample_project/Assets/SampleViewer/Samples/Geocoding/Geocoding.unity
- sample_project/Assets/SampleViewer/Samples/Geometry/Geometries.cs
- sample_project/Assets/SampleViewer/Samples/Geometry/Geometry.unity
- sample_project/Assets/SampleViewer/Samples/HitTest/ArcGISRaycast.cs
- sample_project/Assets/SampleViewer/Samples/HitTest/Hit Test.unity
- sample_project/Assets/SampleViewer/Samples/Measure/Measure.cs
- sample_project/Assets/SampleViewer/Samples/Measure/Measure.unity
- sample_project/Assets/SampleViewer/Samples/Routing/RouteManager.cs
- sample_project/Assets/SampleViewer/Samples/Routing/Routing.unity
- sample_project/Assets/SampleViewer/Samples/StreamLayer/StreamLayer.unity
- sample_project/Assets/SampleViewer/Samples/WeatherQuery/WeatherQuery.unity
- sample_project/Assets/SampleViewer/Scripts/InputManager.cs
- sample_project/Assets/SampleViewer/Scripts/InputManager.cs.meta
**Sample**
- Add an Input manager that has Public events that can run Functions from individual samples
- Restructure each sample to have the functions that run on input to be called using the unity events
**Checklist**
ArcGIS Maps SDK 1.7 w/ Unity 2022
> Enhancement: Input Manager

- sample_project/Assets/SampleViewer/Samples/HitTest/Hit Test.unity
**Summary**
Updates hit test scene to resolve issue in sample viewer.
**Checklist**
2.0
> hit test: update sample to latest scene version

- README.md
**Sample**
Updates the main readme to remove the current version being mentioned.
2.0
> readme: remove version specific message

- sample_project/Assets/Resources/MapmanForUnity/HDRP_Metallic_Standard/MapmanMaterialHDRP.mat
- sample_project/Assets/SampleViewer/Resources/Materials/Gray.mat
- sample_project/Assets/SampleViewer/Resources/Materials/Red.mat
- sample_project/Assets/SampleViewer/Samples/BuildingFilter/BuildingFilter.unity
- sample_project/Assets/SampleViewer/Samples/FeatureLayer/FeatureLayer.unity
- sample_project/Assets/SampleViewer/Samples/Geocoding/Geocoding.unity
- sample_project/Assets/SampleViewer/Samples/Geometry/Geometry.unity
- sample_project/Assets/SampleViewer/Samples/LineOfSight/LineOfSight.unity
- sample_project/Assets/SampleViewer/Samples/MaterialByAttribute/MaterialByAttribute.unity
- sample_project/Assets/SampleViewer/Samples/Measure/Measure.unity
- sample_project/Assets/SampleViewer/Samples/Routing/Routing.unity
- sample_project/Assets/SampleViewer/Samples/StreamLayer/StreamLayer.unity
- sample_project/Assets/SampleViewer/Samples/ThirdPerson/ThirdPerson.unity
- sample_project/Assets/SampleViewer/Samples/Viewshed/Viewshed.unity
- sample_project/Assets/SampleViewer/Samples/WeatherQuery/WeatherQuery.unity
**Summary**
- Re-serializes all scenes with ArcGIS Maps SDK for Unity 2.0
- Updates materials for a couple samples to match pattern in newer unity versions.
**Checklist**
2.0
> Update scenes to latest Maps SDK version

- README.md
> Remove the redundant sentence so users will reference from the tutorial link

- sample_project/Assets/SampleViewer/Samples/BuildingFilter/readme.md
- sample_project/Assets/SampleViewer/Samples/FeatureLayer/readme.md
- sample_project/Assets/SampleViewer/Samples/Geocoding/readme.md
- sample_project/Assets/SampleViewer/Samples/HitTest/readme.md
- sample_project/Assets/SampleViewer/Samples/MaterialByAttribute/readme.md
- sample_project/Assets/SampleViewer/Samples/OverviewMap/readme.md
- sample_project/Assets/SampleViewer/Samples/StreamLayer/readme.md
- sample_project/Assets/SampleViewer/Samples/TimeOfDay/readme.md
- sample_project/Assets/SampleViewer/Samples/WeatherQuery/readme.md
**Sample**
We are bringing more consistency to sample titles so they match with the TOC in public doc (to follow Native Apps doc standard).
**Checklist**
> Bring consistency to sample titles
